sonar.projectKey=cdss_system
sonar.organization=triguiislem-lab
sonar.projectName=CDSS System
sonar.projectVersion=1.0

sonar.sources=backend_template/src,medcity-app/src,cdss_professional/cdss_professional_v4181_patch22_multikg_evidence_validation_exact_fix/apps,cdss_professional/cdss_professional_v4181_patch22_multikg_evidence_validation_exact_fix/services,cdss_professional/cdss_professional_v4181_patch22_multikg_evidence_validation_exact_fix/libs
sonar.tests=cdss_professional/cdss_professional_v4181_patch22_multikg_evidence_validation_exact_fix/tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/test_*.py,**/*_test.py

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/.pytest_cache/**,**/coverage/**,**/*.min.js,**/.env,**/.env.*,**/data/**,**/*.sqlite,**/*.db
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/test_*.py,**/*_test.py,**/database/seed.ts,**/main.ts
sonar.sourceEncoding=UTF-8

sonar.typescript.tsconfigPaths=backend_template/tsconfig.json,medcity-app/tsconfig.json
sonar.javascript.lcov.reportPaths=backend_template/coverage/lcov.info,medcity-app/coverage/lcov.info
sonar.python.version=3.11
