export type CdssEndpointMode =
  | "direct"
  | "kaggle_job"
  | "direct_only"
  | "output_only";

export interface CdssEndpointSpec {
  key: string;
  group: string;
  nestMethod: "GET" | "POST";
  nestPath: string;
  fastapiMethod: "GET" | "POST";
  fastapiPath: string;
  purpose: string;
  mode: CdssEndpointMode;
  notes?: string;
}

export const CDSS_ENDPOINT_CATALOG: CdssEndpointSpec[] = [
  {
    key: "health",
    group: "system",
    nestMethod: "GET",
    nestPath: "/api/cdss/health",
    fastapiMethod: "GET",
    fastapiPath: "/health",
    purpose: "FastAPI process liveness check.",
    mode: "direct_only",
  },
  {
    key: "system.status",
    group: "system",
    nestMethod: "GET",
    nestPath: "/api/cdss/system/status",
    fastapiMethod: "GET",
    fastapiPath: "/v1/system/status",
    purpose: "Runtime configuration and model/cache status.",
    mode: "direct_only",
  },
  {
    key: "system.modelCache",
    group: "system",
    nestMethod: "GET",
    nestPath: "/api/cdss/system/model-cache",
    fastapiMethod: "GET",
    fastapiPath: "/v1/system/model-cache",
    purpose: "Inspect model cache state.",
    mode: "direct_only",
  },
  {
    key: "system.modelCacheWarmup",
    group: "system",
    nestMethod: "POST",
    nestPath: "/api/cdss/system/model-cache/warmup",
    fastapiMethod: "POST",
    fastapiPath: "/v1/system/model-cache/warmup",
    purpose: "Force model cache warmup.",
    mode: "direct_only",
  },
  {
    key: "system.qwenWarmup",
    group: "system",
    nestMethod: "POST",
    nestPath: "/api/cdss/system/qwen/warmup",
    fastapiMethod: "POST",
    fastapiPath: "/v1/system/qwen/warmup",
    purpose: "Explicit Qwen warmup.",
    mode: "direct_only",
  },
  {
    key: "system.readiness",
    group: "system",
    nestMethod: "GET",
    nestPath: "/api/cdss/system/readiness",
    fastapiMethod: "GET",
    fastapiPath: "/v1/system/readiness",
    purpose: "Clinical readiness/resource checks.",
    mode: "direct_only",
  },
  {
    key: "prescriptions.draft",
    group: "prescriptions",
    nestMethod: "POST",
    nestPath: "/api/cdss/prescriptions/draft",
    fastapiMethod: "POST",
    fastapiPath: "/v1/prescriptions/draft",
    purpose:
      "Full CDSS pipeline: draft generation, safety, evidence, localization, audit.",
    mode: "kaggle_job",
  },
  {
    key: "prescriptions.analyze",
    group: "prescriptions",
    nestMethod: "POST",
    nestPath: "/api/cdss/prescriptions/analyze",
    fastapiMethod: "POST",
    fastapiPath: "/v1/prescriptions/analyze",
    purpose: "Clinical analysis without full generation.",
    mode: "kaggle_job",
  },
  {
    key: "prescriptions.evidence",
    group: "prescriptions",
    nestMethod: "POST",
    nestPath: "/api/cdss/prescriptions/evidence",
    fastapiMethod: "POST",
    fastapiPath: "/v1/prescriptions/evidence",
    purpose: "Analysis plus evidence retrieval only.",
    mode: "kaggle_job",
  },
  {
    key: "prescriptions.validate",
    group: "prescriptions",
    nestMethod: "POST",
    nestPath: "/api/cdss/prescriptions/validate-plan",
    fastapiMethod: "POST",
    fastapiPath: "/v1/prescriptions/validate",
    purpose: "Validate an existing therapeutic plan.",
    mode: "kaggle_job",
  },
  {
    key: "prescriptions.localize",
    group: "prescriptions",
    nestMethod: "POST",
    nestPath: "/api/cdss/prescriptions/localize",
    fastapiMethod: "POST",
    fastapiPath: "/v1/prescriptions/localize",
    purpose: "Map generic plan to local Tunisian product candidates.",
    mode: "kaggle_job",
  },
  {
    key: "prescriptions.getByTrace",
    group: "audit",
    nestMethod: "GET",
    nestPath: "/api/cdss/prescriptions/:traceId",
    fastapiMethod: "GET",
    fastapiPath: "/v1/prescriptions/{trace_id}",
    purpose: "Fetch audited prescription record by trace id.",
    mode: "direct_only",
  },
  {
    key: "prescriptions.patientHistory",
    group: "audit",
    nestMethod: "GET",
    nestPath: "/api/cdss/prescriptions/patient/:patientId/history",
    fastapiMethod: "GET",
    fastapiPath: "/v1/prescriptions/patient/{patient_id}/history",
    purpose: "Debug patient CDSS history.",
    mode: "direct_only",
  },
  {
    key: "search.formulary",
    group: "search",
    nestMethod: "GET",
    nestPath: "/api/cdss/formulary/search",
    fastapiMethod: "GET",
    fastapiPath: "/v1/prescriptions/formulary/search",
    purpose: "Search local formulary product candidates.",
    mode: "direct_only",
  },
  {
    key: "search.tnMed",
    group: "search",
    nestMethod: "GET",
    nestPath: "/api/cdss/tn-med/search",
    fastapiMethod: "GET",
    fastapiPath: "/v1/prescriptions/tn-med/search",
    purpose: "Search TN Med enrichment database.",
    mode: "direct_only",
  },
  {
    key: "search.kg",
    group: "search",
    nestMethod: "GET",
    nestPath: "/api/cdss/kg/search",
    fastapiMethod: "GET",
    fastapiPath: "/v1/prescriptions/kg/search",
    purpose: "Search KG facts.",
    mode: "direct_only",
  },
  {
    key: "audit.prescriptionTrace",
    group: "audit",
    nestMethod: "GET",
    nestPath: "/api/cdss/prescriptions/audit/:traceId",
    fastapiMethod: "GET",
    fastapiPath: "/v1/prescriptions/audit/{trace_id}",
    purpose: "Fetch audited pipeline execution.",
    mode: "direct_only",
  },
  {
    key: "audit.reviewPacket",
    group: "audit",
    nestMethod: "GET",
    nestPath: "/api/cdss/prescriptions/audit/:traceId/review-packet",
    fastapiMethod: "GET",
    fastapiPath: "/v1/prescriptions/audit/{trace_id}/review-packet",
    purpose: "Fetch clinician review packet.",
    mode: "direct_only",
  },
  {
    key: "audit.traceRouter",
    group: "audit",
    nestMethod: "GET",
    nestPath: "/api/cdss/audit/traces/:traceId",
    fastapiMethod: "GET",
    fastapiPath: "/v1/audit/traces/{trace_id}",
    purpose: "Fetch trace through FastAPI audit router.",
    mode: "direct_only",
  },
  {
    key: "feedback.trace",
    group: "feedback",
    nestMethod: "POST",
    nestPath: "/api/cdss/prescriptions/:traceId/feedback",
    fastapiMethod: "POST",
    fastapiPath: "/v1/prescriptions/{trace_id}/feedback",
    purpose: "Store structured clinician feedback for a trace.",
    mode: "direct_only",
  },
  {
    key: "feedback.approve",
    group: "feedback",
    nestMethod: "POST",
    nestPath: "/api/cdss/prescriptions/:traceId/approve",
    fastapiMethod: "POST",
    fastapiPath: "/v1/prescriptions/{trace_id}/approve",
    purpose: "Legacy approve wrapper.",
    mode: "direct_only",
  },
  {
    key: "feedback.reject",
    group: "feedback",
    nestMethod: "POST",
    nestPath: "/api/cdss/prescriptions/:traceId/reject",
    fastapiMethod: "POST",
    fastapiPath: "/v1/prescriptions/{trace_id}/reject",
    purpose: "Legacy reject wrapper.",
    mode: "direct_only",
  },
  {
    key: "feedback.revise",
    group: "feedback",
    nestMethod: "POST",
    nestPath: "/api/cdss/prescriptions/:traceId/revise",
    fastapiMethod: "POST",
    fastapiPath: "/v1/prescriptions/{trace_id}/revise",
    purpose: "Legacy revise wrapper.",
    mode: "direct_only",
  },
  {
    key: "feedback.clinician",
    group: "feedback",
    nestMethod: "POST",
    nestPath: "/api/cdss/feedback/clinician",
    fastapiMethod: "POST",
    fastapiPath: "/v1/feedback/clinician",
    purpose: "Lightweight clinician feedback endpoint.",
    mode: "direct_only",
  },
];

export const CDSS_MONITORING_SECTIONS = [
  "overview",
  "pipeline",
  "performance",
  "model",
  "safety",
  "feedback",
  "feedback/summary",
  "retrieval",
  "localization",
  "clinical-quality",
] as const;

export type CdssMonitoringSection = (typeof CDSS_MONITORING_SECTIONS)[number];
