global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: medcity-api
    metrics_path: /api/metrics
    static_configs:
      - targets: ["api:3000"]

  - job_name: medcity-cdss
    metrics_path: /metrics
    static_configs:
      - targets: ["cdss:8000"]

  - job_name: ec2-node
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: docker-containers
    static_configs:
      - targets: ["cadvisor:8080"]
